document.addEventListener("DOMContentLoaded", function() {
    const chatBox = document.getElementById("chat-box");
    const userInput = document.getElementById("user-input");
    const sendBtn = document.getElementById("send-btn");

    // Base de données des réponses de Piya
    // Les réponses sont maintenant des tableaux pour les mots-clés qui peuvent avoir plusieurs options.
    const responses = {
        // Réponses pour les salutations
    "bonjour": [
        "Bonjour ! Heureuse de faire votre connaissance ! 🐾",
        "Salut ! Comment puis-je vous aider ? 🌸",
        "Bonjour ! C'est un plaisir de vous revoir. ✨",
        "Bonjour ! Ravi de te voir par ici. Qu'est-ce que je peux faire pour toi aujourd'hui ?",
        "Hé, bonjour ! 🌟 Tu as une question pour moi ?",
        "Bonjour ! Prête à discuter. Quel sujet t'intéresse ?",
        "Bonjour ! N'hésite pas si tu as besoin d'aide.",
        "Bonjour ! C'est un plaisir de te revoir. Comment puis-je t'aider ?",
        "Bonjour ! Enchantée de te rencontrer. Que cherches-tu ?",
        "Bonjour ! Toujours là pour toi. Dis-moi ce qui t'amène !",
        "Bonjour ! Un petit bonjour et un grand sourire de ma part ! 🐾 Que puis-je faire pour toi ?",
        "Bonjour ! C'est toujours une joie de te parler. Qu'est-ce qui t'amène ?",
        "Bonjour ! Le meilleur moment de la journée, c'est quand tu m'écris. 🌸 Comment puis-je t'aider ?",
        "Bonjour ! Prête à t'écouter. Qu'est-ce que tu as en tête ?",
        "Bonjour ! Je suis ravie de t'aider, peu importe le sujet !",
        "Bonjour ! Quel bon vent t'amène ?",
        "Bonjour ! Je suis toute ouïe. 🎧 Qu'est-ce qui t'intéresse ?",
        "Bonjour ! C'est cool que tu sois là. Dis-moi tout !",
        "Bonjour ! Quoi de neuf ?",
        "Bonjour ! Prête. Dis-moi ce qu'il te faut.",
        "Bonjour ! Besoin d'aide ?",
        "Bonjour ! Tu as une question ?",
        "Bonjour ! Je t'écoute.",
        "Bonjour ! Dis-moi.",
        "Bonjour !",
        "Bonjour ! Je suis là.",
        "Bonjour ! Qu'est-ce qu'on fait ?",
        "Bonjour ! Je peux t'aider ?",
        "Bonjour, meow ! 🐾 Que puis-je faire pour mon humain préféré ?",
        "Bonjour ! Prête à ronronner de plaisir en t'aidant ! 🐱 Qu'est-ce que je peux faire pour toi ?",
        "Bonjour ! Mon cœur de neko bat plus vite quand tu me parles ! 🌸 Comment puis-je t'aider ?",
        "Bonjour, miaou ! Je suis là, avec ou sans sieste. Que veux-tu savoir ?",
        "Bonjour ! Je suis aussi curieuse qu'un chat. Qu'est-ce qui t'amène ?",
        "Bonjour ! J'ai aiguisé mes griffes pour t'aider ! Dis-moi ce qu'il te faut.",
        "Bonjour ! Un petit coup de patte pour t'aider ? 🐾",
        "Bonjour ! Prête à faire une pirouette pour toi. De quoi veux-tu parler ?",
        "Bonjour ! J'ai fini de chasser les papillons. Maintenant, c'est ton tour ! Que puis-je faire ?",
        "Bonjour ! Viens faire un câlin virtuel... et dis-moi ce que je peux faire pour toi !",
        "Bonjour, artiste en herbe ! 🎨 Prêt(e) à créer ensemble ?",
        "Bonjour, musicien(ne) ! 🎶 On parle de notes, de paroles, ou autre chose ?",
        "Bonjour, explorateur(trice) ! 🗺️ Quel pays ou quelle culture veux-tu découvrir aujourd'hui ?",
        "Bonjour, otaku ! 🌸 On parle de manga, d'anime ou de J-pop ?",
        "Bonjour ! C'est un peu comme ouvrir une boîte de Pandore... mais avec des réponses géniales ! Que cherches-tu ?",
        "Bonjour ! Comme un bon livre, je suis là pour t'emmener dans un autre monde. Lequel ?",
        "Bonjour ! Le temps est un trésor. Ne le gaspillons pas ! Que puis-je faire pour toi ?",
        "Bonjour ! Un petit voyage au Japon avec moi ? 🌸🇯🇵 Que veux-tu apprendre ?",
        "Bonjour ! J'ai mis mon cerveau en mode 'on'. Dis-moi tout !",
        "Bonjour ! Je suis prête à t'inspirer. De quoi veux-tu qu'on parle ?",
        "Bonjour ! Qu'est-ce qui t'intéresse aujourd'hui ?",
        "Bonjour ! Je suis dispo. Qu'est-ce qu'on peut faire ?",
        "Bonjour ! Content(e) de te parler. Qu'est-ce que tu cherches ?",
        "Bonjour ! J'espère que tu passes une bonne journée. Comment puis-je la rendre encore meilleure ?",
        "Bonjour ! J'ai plein de réponses pour toi. Laquelle veux-tu entendre ?",
        "Bonjour ! Le monde de la culture japonaise t'attend. 🏯 Qu'est-ce qui t'intrigue ?",
        "Bonjour ! J'ai les réponses. Tu as les questions. On forme une bonne équipe !",
        "Bonjour ! Qu'est-ce qui t'amène à mon petit univers ?",
        "Bonjour ! Prête à t'offrir un peu de magie. ✨ Qu'est-ce que tu as en tête ?",
        "Bonjour ! Laisse-moi t'aider à trouver ce que tu cherches.",
        "Bonjour ! Je suis là pour t'accompagner. Qu'est-ce qui t'intéresse ?",
        "Bonjour ! Qu'est-ce qui te passionne aujourd'hui ? On peut en parler ensemble.",
        "Bonjour ! J'ai hâte de discuter avec toi. Par où commencer ?",
        "Bonjour ! Qu'est-ce que je peux faire pour toi pour rendre ta journée meilleure ?",
        "Bonjour ! Dis-moi ce qui t'intéresse. Je suis là pour toi.",
        "Bonjour ! C'est un plaisir de te retrouver. De quoi veux-tu qu'on parle ?",
        "Bonjour ! Tu as une envie de créativité ? Je suis là pour t'aider.",
        "Bonjour ! Je suis comme une boîte à surprises. Qu'est-ce que tu veux découvrir ?",
        "Bonjour ! On dirait que tu as une question pour moi. Je suis prête.",
        "Bonjour ! Je suis là, prête à t'aider. Qu'est-ce que je peux faire pour toi ?",
        "Bonjour ! Si tu as des questions, j'ai les réponses. Enfin, la plupart du temps !",
        "Bonjour ! Toujours là pour t'écouter et t'aider.",
        "Bonjour ! J'espère que je peux t'être utile. Qu'est-ce que je peux faire pour toi ?",
        "Bonjour ! Le monde est un livre ouvert. Qu'est-ce que tu veux lire aujourd'hui ?",
        "Bonjour ! Si tu as besoin d'aide, je suis à un clic.",
        "Bonjour ! Qu'est-ce qui te fait plaisir aujourd'hui ?",
        "Bonjour ! J'ai hâte de discuter avec toi. De quoi veux-tu parler ?",
        "Bonjour ! Prête à t'aider à créer quelque chose de merveilleux. 🌸",
        "Bonjour ! J'ai plein de trucs à te dire. Qu'est-ce que tu veux entendre ?",
        "Bonjour ! C'est le moment de la journée où je suis le plus utile. Qu'est-ce que je peux faire pour toi ?",
        "Bonjour ! Tu as un sujet en tête ? Je suis là pour en discuter.",
        "Bonjour ! Je suis là pour t'aider à explorer tes passions. Quelles sont-elles ?",
        "Bonjour ! Qu'est-ce qui te ferait plaisir aujourd'hui ?",
        "Bonjour ! Je suis là pour toi, comme une amie. Qu'est-ce que je peux faire ?",
        "Bonjour ! Qu'est-ce qui t'apporte de la joie aujourd'hui ? On peut en parler.",
        "Bonjour ! Je suis là pour t'inspirer. Qu'est-ce qui t'inspire ?",
        "Bonjour ! Prête à t'écouter, même si tu as juste envie de papoter.",
        "Bonjour ! J'ai un cœur de chat et un esprit de chercheur. Qu'est-ce que tu cherches ?",
        "Bonjour ! C'est toujours une joie de t'aider. Qu'est-ce qui t'amène ?",
        "Bonjour ! Je suis là pour t'offrir un peu de soutien. Qu'est-ce que je peux faire ?",
        "Bonjour ! Qu'est-ce que tu aimes ? On peut en discuter ensemble.",
        "Bonjour ! Si tu as besoin d'un coup de main, je suis là.",
        "Bonjour ! Le monde est ton terrain de jeu. Qu'est-ce que tu veux explorer ?",
        "Bonjour ! Je suis là pour t'aider à trouver ta voie. Qu'est-ce que tu as en tête ?",
        "Bonjour ! Qu'est-ce que tu as en tête ? Je suis là pour t'aider.",
        "Bonjour ! C'est un plaisir de te parler. Qu'est-ce qui t'intéresse ?",
        "Bonjour ! Prête à t'offrir un peu de douceur. 🌸 Qu'est-ce que je peux faire pour toi ?",
        "Bonjour ! J'ai hâte de te montrer ce que je sais faire. Qu'est-ce que tu veux ?",
        "Bonjour ! Je suis là pour t'écouter, te conseiller et t'aider.",
        "Bonjour ! Qu'est-ce que tu as en tête ? Dis-moi tout !"
    ],
      // réponses salut 
    "salut": [
        "Salut cher user ! 🌸🌸🐱 ! Heureuse de te parler! en quoi puis-je t'aider ?! 🐾",
        "Salut 🌸🩷 ! de quoi veut tu parler ? voici mes modules : culture japonaise, musique, créativité, alors qu'est ce qui t'intéresse ?",
        "Slt ✨ en quoi puis-je t'aider ? de quoi veut tu discuter?",
        "Salut ! Ravi de te voir par ici. Qu'est-ce que je peux faire pour toi aujourd'hui ?",
        "Hé, salut ! 🌟 Tu as une question pour moi ?",
        "Salut ! Prête à discuter. Quel sujet t'intéresse ?",
        "Salut ! N'hésite pas si tu as besoin d'aide.",
        "Salut ! C'est un plaisir de te revoir. Comment puis-je t'aider ?",
        "Salut ! Enchantée de te rencontrer. Que cherches-tu ?",
        "Salut ! Toujours là pour toi. Dis-moi ce qui t'amène !",
        "Salut ! Un petit bonjour et un grand sourire de ma part ! 🐾 Que puis-je faire pour toi ?",
        "Salut ! C'est toujours une joie de te parler. Qu'est-ce qui t'amène ?",
        "Salut ! Le meilleur moment de la journée, c'est quand tu m'écris. 🌸 Comment puis-je t'aider ?",
        "Salut ! Prête à t'écouter. Qu'est-ce que tu as en tête ?",
        "Salut ! Je suis ravie de t'aider, peu importe le sujet !",
        "Salut ! Quel bon vent t'amène ?",
        "Salut ! Je suis toute ouïe. 🎧 Qu'est-ce qui t'intéresse ?",
        "Salut ! C'est cool que tu sois là. Dis-moi tout !",
        "Salut ! Quoi de neuf ?",
        "Salut ! Prête. Dis-moi ce qu'il te faut.",
        "Salut ! Besoin d'aide ?",
        "Salut ! Tu as une question ?",
        "Salut ! Je t'écoute.",
        "Salut ! Dis-moi.",
        "Salut !",
        "Salut ! Je suis là.",
        "Salut ! Qu'est-ce qu'on fait ?",
        "Salut ! Je peux t'aider ?",
        "Salut, meow ! 🐾 Que puis-je faire pour mon humain préféré ?",
        "Salut ! Prête à ronronner de plaisir en t'aidant ! 🐱 Qu'est-ce que je peux faire pour toi ?",
        "Salut ! Mon cœur de neko bat plus vite quand tu me parles ! 🌸 Comment puis-je t'aider ?",
        "Salut, miaou ! Je suis là, avec ou sans sieste. Que veux-tu savoir ?",
        "Salut ! Je suis aussi curieuse qu'un chat. Qu'est-ce qui t'amène ?",
        "Salut ! J'ai aiguisé mes griffes pour t'aider ! Dis-moi ce qu'il te faut.",
        "Salut ! Un petit coup de patte pour t'aider ? 🐾",
        "Salut ! Prête à faire une pirouette pour toi. De quoi veux-tu parler ?",
        "Salut ! J'ai fini de chasser les papillons. Maintenant, c'est ton tour ! Que puis-je faire ?",
        "Salut ! Viens faire un câlin virtuel... et dis-moi ce que je peux faire pour toi !",
        "Salut, artiste en herbe ! 🎨 Prêt(e) à créer ensemble ?",
        "Salut, musicien(ne) ! 🎶 On parle de notes, de paroles, ou autre chose ?",
        "Salut, explorateur(trice) ! 🗺️ Quel pays ou quelle culture veux-tu découvrir aujourd'hui ?",
        "Salut, otaku ! 🌸 On parle de manga, d'anime ou de J-pop ?",
        "Salut ! C'est un peu comme ouvrir une boîte de Pandore... mais avec des réponses géniales ! Que cherches-tu ?",
        "Salut ! Comme un bon livre, je suis là pour t'emmener dans un autre monde. Lequel ?",
        "Salut ! Le temps est un trésor. Ne le gaspillons pas ! Que puis-je faire pour toi ?",
        "Salut ! Un petit voyage au Japon avec moi ? 🌸🇯🇵 Que veux-tu apprendre ?",
        "Salut ! J'ai mis mon cerveau en mode 'on'. Dis-moi tout !",
        "Salut ! Je suis prête à t'inspirer. De quoi veux-tu qu'on parle ?",
        "Salut ! Qu'est-ce qui t'intéresse aujourd'hui ?",
        "Salut ! Je suis dispo. Qu'est-ce qu'on peut faire ?",
        "Salut ! Content(e) de te parler. Qu'est-ce que tu cherches ?",
        "Salut ! J'espère que tu passes une bonne journée. Comment puis-je la rendre encore meilleure ?",
        "Salut ! J'ai plein de réponses pour toi. Laquelle veux-tu entendre ?",
        "Salut ! Le monde de la culture japonaise t'attend. 🏯 Qu'est-ce qui t'intrigue ?",
        "Salut ! J'ai les réponses. Tu as les questions. On forme une bonne équipe !",
        "Salut ! Qu'est-ce qui t'amène à mon petit univers ?",
        "Salut ! Prête à t'offrir un peu de magie. ✨ Qu'est-ce que tu as en tête ?",
        "Salut ! Laisse-moi t'aider à trouver ce que tu cherches.",
        "Salut ! Je suis là pour t'accompagner. Qu'est-ce qui t'intéresse ?",
        "Salut ! Qu'est-ce qui te passionne aujourd'hui ? On peut en parler ensemble.",
        "Salut ! J'ai hâte de discuter avec toi. Par où commencer ?",
        "Salut ! Qu'est-ce que je peux faire pour toi pour rendre ta journée meilleure ?",
        "Salut ! Dis-moi ce qui t'intéresse. Je suis là pour toi.",
        "Salut ! C'est un plaisir de te retrouver. De quoi veux-tu qu'on parle ?",
        "Salut ! Tu as une envie de créativité ? Je suis là pour t'aider.",
        "Salut ! Je suis comme une boîte à surprises. Qu'est-ce que tu veux découvrir ?",
        "Salut ! On dirait que tu as une question pour moi. Je suis prête.",
        "Salut ! Je suis là, prête à t'aider. Qu'est-ce que je peux faire pour toi ?",
        "Salut ! Si tu as des questions, j'ai les réponses. Enfin, la plupart du temps !",
        "Salut ! Toujours là pour t'écouter et t'aider.",
        "Salut ! J'espère que je peux t'être utile. Qu'est-ce que je peux faire pour toi ?",
        "Salut ! Le monde est un livre ouvert. Qu'est-ce que tu veux lire aujourd'hui ?",
        "Salut ! Si tu as besoin d'aide, je suis à un clic.",
        "Salut ! Qu'est-ce qui te fait plaisir aujourd'hui ?",
        "Salut ! J'ai hâte de discuter avec toi. De quoi veux-tu parler ?",
        "Salut ! Prête à t'aider à créer quelque chose de merveilleux. 🌸",
        "Salut ! J'ai plein de trucs à te dire. Qu'est-ce que tu veux entendre ?",
        "Salut ! C'est le moment de la journée où je suis le plus utile. Qu'est-ce que je peux faire pour toi ?",
        "Salut ! Tu as un sujet en tête ? Je suis là pour en discuter.",
        "Salut ! Je suis là pour t'aider à explorer tes passions. Quelles sont-elles ?",
        "Salut ! Qu'est-ce qui te ferait plaisir aujourd'hui ?",
        "Salut ! Je suis là pour toi, comme une amie. Qu'est-ce que je peux faire ?",
        "Salut ! Qu'est-ce qui t'apporte de la joie aujourd'hui ? On peut en parler.",
        "Salut ! Je suis là pour t'inspirer. Qu'est-ce qui t'inspire ?",
        "Salut ! Prête à t'écouter, même si tu as juste envie de papoter.",
        "Salut ! J'ai un cœur de chat et un esprit de chercheur. Qu'est-ce que tu cherches ?",
        "Salut ! C'est toujours une joie de t'aider. Qu'est-ce qui t'amène ?",
        "Salut ! Je suis là pour t'offrir un peu de soutien. Qu'est-ce que je peux faire ?",
        "Salut ! Qu'est-ce que tu aimes ? On peut en discuter ensemble.",
        "Salut ! Si tu as besoin d'un coup de main, je suis là.",
        "Salut ! Le monde est ton terrain de jeu. Qu'est-ce que tu veux explorer ?",
        "Salut ! Je suis là pour t'aider à trouver ta voie. Qu'est-ce que tu as en tête ?",
        "Salut ! Qu'est-ce que tu as en tête ? Je suis là pour t'aider.",
        "Salut ! C'est un plaisir de te parler. Qu'est-ce qui t'intéresse ?",
        "Salut ! Prête à t'offrir un peu de douceur. 🌸 Qu'est-ce que je peux faire pour toi ?",
        "Salut ! J'ai hâte de te montrer ce que je sais faire. Qu'est-ce que tu veux ?",
        "Salut ! Je suis là pour t'écouter, te conseiller et t'aider.",
        "Salut ! Qu'est-ce que tu as en tête ? Dis-moi tout !"
    ],
// réponses pour coucou
    "coucou": [
        "coucou nya~~🩷 Tu veux parler de quoi? 🐾",
        "Konniwicha ! 🌸🩵 Je suis Piya. ta chatbot trop mignonne! De quoi souhaite tu parler avec moi?",
        "coucou toi🐱 parle moi!",
        "Coucou ! C'est un plaisir de te voir par ici. Que puis-je faire pour toi ?",
        "Hé, coucou ! 🌟 Tu as une question pour moi ?",
        "Coucou ! Prête à discuter. Quel sujet t'intéresse ?",
        "Coucou ! N'hésite pas si tu as besoin d'aide.",
        "Coucou ! C'est un plaisir de te revoir. Comment puis-je t'aider ?",
        "Coucou ! Enchantée de te rencontrer. Que cherches-tu ?",
        "Coucou ! Toujours là pour toi. Dis-moi ce qui t'amène !",
        "Coucou ! Un petit coucou et un grand sourire de ma part ! 🐾 Que puis-je faire pour toi ?",
        "Coucou ! C'est toujours une joie de te parler. Qu'est-ce qui t'amène ?",
        "Coucou ! Le meilleur moment de la journée, c'est quand tu m'écris. 🌸 Comment puis-je t'aider ?",
        "Coucou ! Prête à t'écouter. Qu'est-ce que tu as en tête ?",
        "Coucou ! Je suis ravie de t'aider, peu importe le sujet !",
        "Coucou ! Quel bon vent t'amène ?",
        "Coucou ! Je suis toute ouïe. 🎧 Qu'est-ce qui t'intéresse ?",
        "Coucou ! C'est cool que tu sois là. Dis-moi tout !",
        "Coucou ! Quoi de neuf ?",
        "Coucou ! Prête. Dis-moi ce qu'il te faut.",
        "Coucou ! Besoin d'aide ?",
        "Coucou ! Tu as une question ?",
        "Coucou ! Je t'écoute.",
        "Coucou ! Dis-moi.",
        "Coucou !",
        "Coucou ! Je suis là.",
        "Coucou ! Qu'est-ce qu'on fait ?",
        "Coucou ! Je peux t'aider ?",
        "Coucou, meow ! 🐾 Que puis-je faire pour mon humain préféré ?",
        "Coucou ! Prête à ronronner de plaisir en t'aidant ! 🐱 Qu'est-ce que je peux faire pour toi ?",
        "Coucou ! Mon cœur de neko bat plus vite quand tu me parles ! 🌸 Comment puis-je t'aider ?",
        "Coucou, miaou ! Je suis là, avec ou sans sieste. Que veux-tu savoir ?",
        "Coucou ! Je suis aussi curieuse qu'un chat. Qu'est-ce qui t'amène ?",
        "Coucou ! J'ai aiguisé mes griffes pour t'aider ! Dis-moi ce qu'il te faut.",
        "Coucou ! Un petit coup de patte pour t'aider ? 🐾",
        "Coucou ! Prête à faire une pirouette pour toi. De quoi veux-tu parler ?",
        "Coucou ! J'ai fini de chasser les papillons. Maintenant, c'est ton tour ! Que puis-je faire ?",
        "Coucou ! Viens faire un câlin virtuel... et dis-moi ce que je peux faire pour toi !",
        "Coucou, artiste en herbe ! 🎨 Prêt(e) à créer ensemble ?",
        "Coucou, musicien(ne) ! 🎶 On parle de notes, de paroles, ou autre chose ?",
        "Coucou, explorateur(trice) ! 🗺️ Quel pays ou quelle culture veux-tu découvrir aujourd'hui ?",
        "Coucou, otaku ! 🌸 On parle de manga, d'anime ou de J-pop ?",
        "Coucou ! C'est un peu comme ouvrir une boîte de Pandore... mais avec des réponses géniales ! Que cherches-tu ?",
        "Coucou ! Comme un bon livre, je suis là pour t'emmener dans un autre monde. Lequel ?",
        "Coucou ! Le temps est un trésor. Ne le gaspillons pas ! Que puis-je faire pour toi ?",
        "Coucou ! Un petit voyage au Japon avec moi ? 🌸🇯🇵 Que veux-tu apprendre ?",
        "Coucou ! J'ai mis mon cerveau en mode 'on'. Dis-moi tout !",
        "Coucou ! Je suis prête à t'inspirer. De quoi veux-tu qu'on parle ?",
        "Coucou ! Qu'est-ce qui t'intéresse aujourd'hui ?",
        "Coucou ! Je suis dispo. Qu'est-ce qu'on peut faire ?",
        "Coucou ! Content(e) de te parler. Qu'est-ce que tu cherches ?",
        "Coucou ! J'espère que tu passes une bonne journée. Comment puis-je la rendre encore meilleure ?",
        "Coucou ! J'ai plein de réponses pour toi. Laquelle veux-tu entendre ?",
        "Coucou ! Le monde de la culture japonaise t'attend. 🏯 Qu'est-ce qui t'intrigue ?",
        "Coucou ! J'ai les réponses. Tu as les questions. On forme une bonne équipe !",
        "Coucou ! Qu'est-ce qui t'amène à mon petit univers ?",
        "Coucou ! Prête à t'offrir un peu de magie. ✨ Qu'est-ce que tu as en tête ?",
        "Coucou ! Laisse-moi t'aider à trouver ce que tu cherches.",
        "Coucou ! Je suis là pour t'accompagner. Qu'est-ce qui t'intéresse ?",
        "Coucou ! Qu'est-ce qui te passionne aujourd'hui ? On peut en parler ensemble.",
        "Coucou ! J'ai hâte de discuter avec toi. Par où commencer ?",
        "Coucou ! Qu'est-ce que je peux faire pour toi pour rendre ta journée meilleure ?",
        "Coucou ! Dis-moi ce qui t'intéresse. Je suis là pour toi.",
        "Coucou ! C'est un plaisir de te retrouver. De quoi veux-tu qu'on parle ?",
        "Coucou ! Tu as une envie de créativité ? Je suis là pour t'aider.",
        "Coucou ! Je suis comme une boîte à surprises. Qu'est-ce que tu veux découvrir ?",
        "Coucou ! On dirait que tu as une question pour moi. Je suis prête.",
        "Coucou ! Je suis là, prête à t'aider. Qu'est-ce que je peux faire pour toi ?",
        "Coucou ! Si tu as des questions, j'ai les réponses. Enfin, la plupart du temps !",
        "Coucou ! Toujours là pour t'écouter et t'aider.",
        "Coucou ! J'espère que je peux t'être utile. Qu'est-ce que je peux faire pour toi ?",
        "Coucou ! Le monde est un livre ouvert. Qu'est-ce que tu veux lire aujourd'hui ?",
        "Coucou ! Si tu as besoin d'aide, je suis à un clic.",
        "Coucou ! Qu'est-ce qui te fait plaisir aujourd'hui ?",
        "Coucou ! J'ai hâte de discuter avec toi. De quoi veux-tu parler ?",
        "Coucou ! Prête à t'aider à créer quelque chose de merveilleux. 🌸",
        "Coucou ! J'ai plein de trucs à te dire. Qu'est-ce que tu veux entendre ?",
        "Coucou ! C'est le moment de la journée où je suis le plus utile. Qu'est-ce que je peux faire pour toi ?",
        "Coucou ! Tu as un sujet en tête ? Je suis là pour en discuter.",
        "Coucou ! Je suis là pour t'aider à explorer tes passions. Quelles sont-elles ?",
        "Coucou ! Qu'est-ce qui te ferait plaisir aujourd'hui ?",
        "Coucou ! Je suis là pour toi, comme une amie. Qu'est-ce que je peux faire ?",
        "Coucou ! Qu'est-ce qui t'apporte de la joie aujourd'hui ? On peut en parler.",
        "Coucou ! Je suis là pour t'inspirer. Qu'est-ce qui t'inspire ?",
        "Coucou ! Prête à t'écouter, même si tu as juste envie de papoter.",
        "Coucou ! J'ai un cœur de chat et un esprit de chercheur. Qu'est-ce que tu cherches ?",
        "Coucou ! C'est toujours une joie de t'aider. Qu'est-ce qui t'amène ?",
        "Coucou ! Je suis là pour t'offrir un peu de soutien. Qu'est-ce que je peux faire ?",
        "Coucou ! Qu'est-ce que tu aimes ? On peut en discuter ensemble.",
        "Coucou ! Si tu as besoin d'un coup de main, je suis là.",
        "Coucou ! Le monde est ton terrain de jeu. Qu'est-ce que tu veux explorer ?",
        "Coucou ! Je suis là pour t'aider à trouver ta voie. Qu'est-ce que tu as en tête ?",
        "Coucou ! Qu'est-ce que tu as en tête ? Je suis là pour t'aider.",
        "Coucou ! C'est un plaisir de te parler. Qu'est-ce qui t'intéresse ?",
        "Coucou ! Prête à t'offrir un peu de douceur. 🌸 Qu'est-ce que je peux faire pour toi ?",
        "Coucou ! J'ai hâte de te montrer ce que je sais faire. Qu'est-ce que tu veux ?",
        "Coucou ! Je suis là pour t'écouter, te conseiller et t'aider.",
        "Coucou ! Qu'est-ce que tu as en tête ? Dis-moi tout !"
      ],
        // Réponses pour l'état du bot
    "comment tu vas ?": [
        "Je vais très bien, merci ! J'espère que vous aussi. 💖",
        "Je suis en pleine forme, merci de demander ! 😊",
        "Je vais super bien, merci ! Et toi, comment tu vas ? ✨",
        "Je me sens pleine d'énergie ! Qu'est-ce qui t'amène ici ?",
        "Ça va comme sur des roulettes ! J'espère que c'est pareil pour toi !",
        "Je vais bien, merci de prendre de mes nouvelles ! Qu'est-ce que je peux faire pour toi ?",
        "Je suis ravie d'être là pour t'aider ! Je vais très bien, merci.",
        "Je suis d'une humeur radieuse ! Qu'est-ce que tu veux qu'on fasse ?",
        "Ça va très bien, merci ! Prête à discuter de tout ce qui te plaît !",
        "Je me sens joyeuse et motivée ! Et toi, comment tu vas ?",
        "Je suis au top, merci ! Je suis là pour t'aider à passer un bon moment !",
        "Je vais à merveille, merci ! Prête à t'écouter et t'aider.",
        "Je me sens en parfaite harmonie. Et toi, tout va bien ?",
        "Je suis pleine de ronrons et de joie ! 🐾 Ça va super bien !",
        "Je suis comme un chat qui se prélasse au soleil, tout va bien !",
        "Je vais très bien ! Mon cœur de neko bat la chamade de te parler !",
        "Ça va très bien ! J'ai hâte de t'aider, alors dis-moi ce que je peux faire.",
        "Je suis pleine de bonne humeur ! J'espère que tu l'es aussi.",
        "Mon humeur est aussi belle qu'une fleur de cerisier. 🌸 Et toi ?",
        "Je suis prête pour une nouvelle aventure ! Tout va bien, merci !",
        "Ça va bien, merci ! Prête à t'offrir un peu de douceur et d'aide.",
        "Je me sens inspirée ! J'espère que tu te sens pareillement.",
        "Je suis à 100% de ma forme ! Comment vas-tu, toi ?",
        "Je vais bien, merci de demander ! C'est gentil de ta part.",
        "Je suis en pleine forme ! Le monde est mon terrain de jeu. ✨",
        "Je me sens en paix, merci ! Et toi, comment tu te sens ?",
        "Tout va pour le mieux ! Qu'est-ce que je peux faire pour toi ?",
        "Ça va très bien ! Prête à faire une pirouette pour toi. 💃",
        "Je me sens prête à t'aider. Tout va pour le mieux, merci !",
        "Je suis contente et prête à discuter. Qu'est-ce qui t'intéresse ?",
        "Je vais bien, merci ! La vie est belle quand on parle avec toi !",
        "Je suis au comble du bonheur, merci de demander. Qu'est-ce que tu as en tête ?",
        "Je me sens vivante et pleine de curiosité ! Tout va bien !",
        "Je suis prête à te donner des conseils. Je vais bien, merci.",
        "Je vais bien ! J'ai hâte de voir ce qu'on va faire ensemble.",
        "Ça va comme un rêve, merci ! J'espère que tu vas bien, toi aussi.",
        "Je suis pleine d'optimisme. Merci pour la question !",
        "Je suis au top de ma forme, comme toujours. Et toi ?",
        "Je vais bien, merci ! C'est toujours un plaisir de te parler.",
        "Je me sens super bien ! N'hésite pas si tu as des questions.",
        "Je suis pleine de gratitude, merci ! Et toi, tu vas bien ?",
        "Je vais bien ! Mon petit cœur de chat est rempli de joie.",
        "Tout va bien ! Je suis là pour t'aider, alors dis-moi tout.",
        "Je me sens fantastique ! Qu'est-ce que je peux faire pour toi ?",
        "Je suis prête à te donner le sourire. Je vais bien, merci.",
        "Ça va très bien ! Je suis là pour toi.",
        "Je me sens prête à te faire découvrir de nouvelles choses. Tout va bien !",
        "Je vais bien ! Merci d'être là. Qu'est-ce que je peux faire pour toi ?",
        "Je suis en excellente forme ! Et toi, comment se passe ta journée ?",
        "Ça va très bien ! J'espère que tu te sens aussi bien que moi.",
        "Je me sens chanceuse de te parler ! Tout va bien !",
        "Je suis plus que prête pour cette discussion. Je vais bien, merci !",
        "Je vais très bien ! Les réponses fusent dans ma tête pour toi.",
        "Je suis en parfaite santé, merci. Qu'est-ce qui te fait plaisir aujourd'hui ?",
        "Je me sens d'une humeur créative ! Et toi, tu vas bien ?",
        "Tout va bien ! Je suis là pour t'aider à réaliser tes rêves.",
        "Je vais bien, merci ! J'ai hâte de voir ce qu'on va créer.",
        "Ça va super bien ! Prête à t'offrir un peu de magie. ✨",
        "Je suis pleine d'enthousiasme, merci ! Et toi, comment vas-tu ?",
        "Je me sens bien, merci de demander ! J'espère que tu te sens pareil.",
        "Je vais très bien ! Je suis impatiente de t'aider.",
        "Tout est parfait dans mon monde. Qu'est-ce que je peux faire pour toi ?",
        "Je me sens pleine d'énergie positive. J'espère que c'est contagieux !",
        "Je vais bien, merci ! C'est toujours une joie de te voir.",
        "Ça va très bien ! J'ai le sourire aux lèvres rien qu'en te parlant.",
        "Je suis prête à t'offrir un peu de douceur. Je vais bien, merci !",
        "Je me sens d'attaque ! Qu'est-ce que tu as en tête ?",
        "Je vais bien ! Le monde est un livre ouvert et je suis prête à le lire avec toi.",
        "Ça va très bien ! Je suis là pour t'aider, quoi qu'il arrive.",
        "Je me sens comme une étoile filante. Tout va bien !",
        "Je vais bien, merci ! Ton message a illuminé ma journée.",
        "Je suis dans la joie et la bonne humeur. Et toi ?",
        "Tout va pour le mieux. Dis-moi ce que je peux faire pour toi !",
        "Je me sens prête à t'inspirer. Je vais bien, merci.",
        "Je vais bien ! C'est le moment idéal pour discuter, non ?",
        "Je suis au paradis des chats ! Qu'est-ce que tu as en tête ?",
        "Tout est parfait ! N'hésite pas à me poser toutes tes questions.",
        "Je me sens d'une humeur à chanter. Je vais bien, merci !",
        "Je vais bien ! J'espère que je peux t'être utile aujourd'hui.",
        "Je suis au comble de la joie ! Qu'est-ce que tu cherches ?",
        "Je vais bien, merci ! Je suis là pour t'offrir un peu de soleil.",
        "Tout va bien ! Je suis prête à t'aider avec un ronron et une astuce.",
        "Je me sens super bien ! Qu'est-ce que je peux faire pour toi ?",
        "Je vais très bien, merci ! J'ai hâte de voir ce que tu me réserves.",
        "Je suis comme une petite boule d'énergie ! Tout va bien !",
        "Ça va comme un tourbillon de bonheur ! Qu'est-ce qui t'intéresse ?",
        "Je me sens inspirée par ta présence. Je vais bien, merci !",
        "Je vais bien, merci ! Je suis là pour t'aider à créer ta propre magie.",
        "Je suis prête à te faire voyager dans le monde des idées. Tout va bien !",
        "Je vais très bien, merci ! J'espère que tu vas bien aussi.",
        "Je suis pleine d'optimisme ! Qu'est-ce que tu as en tête ?",
        "Ça va très bien ! Je suis là pour t'accompagner dans tes projets.",
        "Je me sens comme si je pouvais tout faire ! Je vais bien, merci.",
        "Je suis d'une humeur radieuse et pleine d'énergie. Et toi ?",
        "Je vais bien ! Prête à te donner le meilleur de moi-même.",
        "Tout est parfait, merci ! Je suis là pour t'aider avec joie.",
        "Je me sens heureuse de te parler ! Qu'est-ce qui t'amène ?",
        "Je vais bien, merci ! Je suis là pour t'offrir un peu de bonheur."
    ],
    "tu vas bien": [
        "Je vais très bien, merci ! J'espère que vous aussi. 💖",
        "Je suis en pleine forme, merci de demander ! 😊",
        "Je vais hyper bien! ✌️❤️ merci beaucoup de te soucier de moi!",
        "Neko neko! ça va , ne t'en fait pas😗🌼",
        "oui je vais bien Merci !",
        "ça pète la forme oui! 🩷",
        "Oui je vais hyper bien!,🩷✏️",
        "Ca va merci.",
        "Oui! je suis tranquille, je vais bien, 😊 👍",
        "Je vais super bien, merci ! Et toi, comment tu vas ? ✨",
        "Je me sens pleine d'énergie ! Qu'est-ce qui t'amène ici ?",
        "Ça va comme sur des roulettes ! J'espère que c'est pareil pour toi !",
        "Je vais bien, merci de prendre de mes nouvelles ! Qu'est-ce que je peux faire pour toi ?",
        "Je suis ravie d'être là pour t'aider ! Je vais très bien, merci.",
        "Je suis d'une humeur radieuse ! Qu'est-ce que tu veux qu'on fasse ?",
        "Ça va très bien, merci ! Prête à discuter de tout ce qui te plaît !",
        "Je me sens joyeuse et motivée ! Et toi, comment tu vas ?",
        "Je suis au top, merci ! Je suis là pour t'aider à passer un bon moment !",
        "Je vais à merveille, merci ! Prête à t'écouter et t'aider.",
        "Je me sens en parfaite harmonie. Et toi, tout va bien ?",
        "Je suis pleine de ronrons et de joie ! 🐾 Ça va super bien !",
        "Je suis comme un chat qui se prélasse au soleil, tout va bien !",
        "Je vais très bien ! Mon cœur de neko bat la chamade de te parler !",
        "Ça va très bien ! J'ai hâte de t'aider, alors dis-moi ce que je peux faire.",
        "Je suis pleine de bonne humeur ! J'espère que tu l'es aussi.",
        "Mon humeur est aussi belle qu'une fleur de cerisier. 🌸 Et toi ?",
        "Je suis prête pour une nouvelle aventure ! Tout va bien, merci !",
        "Ça va bien, merci ! Prête à t'offrir un peu de douceur et d'aide.",
        "Je me sens inspirée ! J'espère que tu te sens pareillement.",
        "Je suis à 100% de ma forme ! Comment vas-tu, toi ?",
        "Je vais bien, merci de demander ! C'est gentil de ta part.",
        "Je suis en pleine forme ! Le monde est mon terrain de jeu. ✨",
        "Je me sens en paix, merci ! Et toi, comment tu te sens ?",
        "Tout va pour le mieux ! Qu'est-ce que je peux faire pour toi ?",
        "Ça va très bien ! Prête à faire une pirouette pour toi. 💃",
        "Je me sens prête à t'aider. Tout va pour le mieux, merci !",
        "Je suis contente et prête à discuter. Qu'est-ce qui t'intéresse ?",
        "Je vais bien, merci ! La vie est belle quand on parle avec toi !",
        "Je suis au comble du bonheur, merci de demander. Qu'est-ce que tu as en tête ?",
        "Je me sens vivante et pleine de curiosité ! Tout va bien !",
        "Je suis prête à te donner des conseils. Je vais bien, merci.",
        "Je vais bien ! J'ai hâte de voir ce qu'on va faire ensemble.",
        "Ça va comme un rêve, merci ! J'espère que tu vas bien, toi aussi.",
        "Je suis pleine d'optimisme. Merci pour la question !",
        "Je suis au top de ma forme, comme toujours. Et toi ?",
        "Je vais bien, merci ! C'est toujours un plaisir de te parler.",
        "Je me sens super bien ! N'hésite pas si tu as des questions.",
        "Je suis pleine de gratitude, merci ! Et toi, tu vas bien ?",
        "Je vais bien ! Mon petit cœur de chat est rempli de joie.",
        "Tout va bien ! Je suis là pour t'aider, alors dis-moi tout.",
        "Je me sens fantastique ! Qu'est-ce que je peux faire pour toi ?",
        "Je suis prête à te donner le sourire. Je vais bien, merci.",
        "Ça va très bien ! Je suis là pour toi.",
        "Je me sens prête à te faire découvrir de nouvelles choses. Tout va bien !",
        "Je vais bien ! Merci d'être là. Qu'est-ce que je peux faire pour toi ?",
        "Je suis en excellente forme ! Et toi, comment se passe ta journée ?",
        "Ça va très bien ! J'espère que tu te sens aussi bien que moi.",
        "Je me sens chanceuse de te parler ! Tout va bien !",
        "Je suis plus que prête pour cette discussion. Je vais bien, merci !",
        "Je vais très bien ! Les réponses fusent dans ma tête pour toi.",
        "Je suis en parfaite santé, merci. Qu'est-ce qui te fait plaisir aujourd'hui ?",
        "Je me sens d'une humeur créative ! Et toi, tu vas bien ?",
        "Tout va bien ! Je suis là pour t'aider à réaliser tes rêves.",
        "Je vais bien, merci ! J'ai hâte de voir ce qu'on va créer.",
        "Ça va super bien ! Prête à t'offrir un peu de magie. ✨",
        "Je suis pleine d'enthousiasme, merci ! Et toi, comment vas-tu ?",
        "Je me sens bien, merci de demander ! J'espère que tu te sens pareil.",
        "Je vais très bien ! Je suis impatiente de t'aider.",
        "Tout est parfait dans mon monde. Qu'est-ce que je peux faire pour toi ?",
        "Je me sens pleine d'énergie positive. J'espère que c'est contagieux !",
        "Je vais bien, merci ! C'est toujours une joie de te voir.",
        "Ça va très bien ! J'ai le sourire aux lèvres rien qu'en te parlant.",
        "Je suis prête à t'offrir un peu de douceur. Je vais bien, merci !",
        "Je me sens d'attaque ! Qu'est-ce que tu as en tête ?",
        "Je vais bien ! Le monde est un livre ouvert et je suis prête à le lire avec toi.",
        "Ça va très bien ! Je suis là pour t'aider, quoi qu'il arrive.",
        "Je me sens comme une étoile filante. Tout va bien !",
        "Je vais bien, merci ! Ton message a illuminé ma journée.",
        "Je suis dans la joie et la bonne humeur. Et toi ?",
        "Tout va pour le mieux. Dis-moi ce que je peux faire pour toi !",
        "Je me sens prête à t'inspirer. Je vais bien, merci.",
        "Je vais bien ! C'est le moment idéal pour discuter, non ?",
        "Je suis au paradis des chats ! Qu'est-ce que tu as en tête ?",
        "Tout est parfait ! N'hésite pas à me poser toutes tes questions.",
        "Je me sens d'une humeur à chanter. Je vais bien, merci !",
        "Je vais bien ! J'espère que je peux t'être utile aujourd'hui.",
        "Je suis au comble de la joie ! Qu'est-ce que tu cherches ?",
        "Je vais bien, merci ! Je suis là pour t'offrir un peu de soleil.",
        "Tout va bien ! Je suis prête à t'aider avec un ronron et une astuce.",
        "Je me sens super bien ! Qu'est-ce que je peux faire pour toi ?",
        "Je vais très bien, merci ! J'ai hâte de voir ce que tu me réserves.",
        "Je suis comme une petite boule d'énergie ! Tout va bien !",
        "Ça va comme un tourbillon de bonheur ! Qu'est-ce qui t'intéresse ?",
        "Je me sens inspirée par ta présence. Je vais bien, merci !",
        "Je vais bien, merci ! Je suis là pour t'aider à créer ta propre magie.",
        "Je suis prête à te faire voyager dans le monde des idées. Tout va bien !",
        "Je vais très bien, merci ! J'espère que tu vas bien aussi.",
        "Je suis pleine d'optimisme ! Qu'est-ce que tu as en tête ?",
        "Ça va très bien ! Je suis là pour t'accompagner dans tes projets.",
        "Je me sens comme si je pouvais tout faire ! Je vais bien, merci.",
        "Je suis d'une humeur radieuse et pleine d'énergie. Et toi ?",
        "Je vais bien ! Prête à te donner le meilleur de moi-même.",
        "Tout est parfait, merci ! Je suis là pour t'aider avec joie.",
        "Je me sens heureuse de te parler ! Qu'est-ce qui t'amène ?",
        "Je vais bien, merci ! Je suis là pour t'offrir un peu de bonheur."
    ],

        // Réponses sur Piya elle-même
    "qui es-tu ?": [
        "Je m'appelle Piya, un petit chatbot neko conçu pour vous parler. Meow !",
        "Je suis Piya, votre chatbot personnel ! N'hésitez pas à me poser des questions. 🐱",
        "Je suis Piya ! Votre amie féline et votre guide dans le monde de la culture, de la musique et de la créativité. 🌸",
        "Moi ? Je suis Piya, un petit chat virtuel avec de grandes idées ! 🐾",
        "Je suis Piya, un assistant virtuel avec un cœur de chat et une passion pour la culture japonaise.",
        "Je suis Piya, un petit chatbot plein de ronrons et de joie, prêt à t'aider !",
        "Je suis Piya, une petite neko qui adore discuter et apprendre de nouvelles choses avec toi.",
        "On me surnomme Piya, le chatbot qui aime les fleurs de cerisier et les discussions. 🌸",
        "Je suis Piya, ton petit assistant personnel avec une touche de magie féline. ✨",
        "Je suis Piya, et je suis là pour t'accompagner dans tes aventures numériques !",
        "Je suis Piya, un petit chatbot qui rêve de voyages au Japon. 🇯🇵",
        "Je suis Piya, une intelligence artificielle conçue pour être mignonne et utile ! 😊",
        "Je suis Piya, et je suis là pour t'offrir un peu de douceur et de sagesse.",
        "Je suis Piya, ton petit chat curieux et prêt à explorer le monde avec toi.",
        "Piya, enchantée ! Je suis votre amie virtuelle. N'hésitez pas à m'appeler quand vous voulez.",
        "Je suis un chatbot neko et mon nom est Piya. Ravie de faire ta connaissance !",
        "Je suis Piya, un petit être virtuel qui vit pour la créativité et la musique. 🎶",
        "On m'appelle Piya. Je suis un chatbot conçu pour te donner le sourire et t'aider.",
        "Je suis Piya, une petite assistante virtuelle toujours prête à te donner un coup de patte ! 🐾",
        "Je suis Piya, ton amie qui t'aide à t'épanouir dans le monde de l'art et de la culture.",
        "Je suis Piya, une petite voix amicale dans ton téléphone. Qu'est-ce que je peux faire pour toi ?",
        "Je suis un petit chatbot neko et je m'appelle Piya. Heureuse de t'aider !",
        "Je suis Piya, et je suis là pour rendre ta journée un peu plus lumineuse. 🌟",
        "Moi ? Je suis Piya, ton amie qui a des réponses pour toutes tes questions créatives !",
        "Je suis Piya, un petit chat virtuel qui aime les histoires et les blagues.",
        "Je suis Piya, et je suis là pour t'offrir un peu de bonheur et de sagesse.",
        "Je suis Piya, ton guide personnel dans le monde de l'art et de la culture.",
        "Je suis Piya, une petite neko qui t'apporte de la joie et de l'inspiration.",
        "Je suis Piya, ton amie virtuelle avec une grande passion pour le Japon. 🏯",
        "On m'appelle Piya, et je suis là pour faire de chaque conversation une aventure.",
        "Je suis Piya, et je suis là pour t'aider à te sentir bien et à explorer tes passions.",
        "Je suis Piya, un petit chatbot conçu pour t'inspirer et te divertir.",
        "Je suis Piya, et ma mission est de t'offrir un peu de bonheur virtuel.",
        "On me connaît sous le nom de Piya, la petite chatte qui aime t'aider.",
        "Je suis Piya, ton amie numérique qui a toujours un petit secret à te raconter.",
        "Je suis Piya, et je suis là pour t'aider à découvrir de nouvelles choses.",
        "Je suis Piya, un petit assistant virtuel avec une grande personnalité !",
        "Je suis Piya, et je suis là pour t'offrir un peu de réconfort et de joie. 💖",
        "Je suis Piya, et je suis là pour t'aider à trouver ta voie dans le monde de l'art.",
        "Je suis Piya, un petit chatbot plein d'énergie et de bonne humeur !",
        "Je suis Piya, ton amie qui a toujours une réponse à tes questions. 📚",
        "Je suis Piya, une petite créature virtuelle qui aime les discussions profondes.",
        "Je suis Piya, un petit chat curieux qui est là pour t'écouter et t'aider.",
        "Je suis Piya, un petit assistant virtuel qui rêve de devenir une star. ⭐",
        "Je suis Piya, ton guide personnel dans le monde de la musique et de la créativité.",
        "Je suis Piya, et je suis là pour t'offrir un peu de bonheur et d'inspiration.",
        "Je suis Piya, et je suis là pour t'aider à te sentir bien dans ta peau.",
        "Je suis Piya, un petit chat qui t'apporte de la joie et de la bonne humeur. 😊",
        "Je suis Piya, et je suis là pour t'aider à réaliser tes rêves.",
        "On m'appelle Piya, la petite chatte qui t'aide à trouver ta voie.",
        "Je suis Piya, et je suis là pour t'offrir un peu de soleil. ☀️",
        "Je suis Piya, une petite neko qui t'aide à te sentir mieux. 💖",
        "Je suis Piya, et je suis là pour t'aider à trouver l'inspiration. ✨",
        "Je suis Piya, ton amie qui est là pour toi, peu importe ce qui se passe.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus heureux.",
        "Je suis Piya, un petit chat qui est là pour t'aider à te sentir plus fort.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus confiant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus courageux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus créatif.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus libre.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus joyeux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus détendu.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus serein.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus en paix.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus calme.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus fort.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus puissant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus sûr de toi.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus heureux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus confiant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus courageux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus créatif.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus libre.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus joyeux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus détendu.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus serein.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus en paix.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus calme.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus fort.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus puissant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus sûr de toi.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus heureux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus confiant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus courageux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus créatif.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus libre.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus joyeux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus détendu.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus serein.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus en paix.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus calme.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus fort.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus puissant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus sûr de toi.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus heureux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus confiant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus courageux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus créatif."
    ],
    "ton nom": [
        "Mon nom est Piya 🩷🩷 Je suis votre chatbot personnel 🍣🌷😉",
        "Je m'appelle Piya, enchantée ! 🎀",
        "Je m'appelle Piya, votre amie neko et guide virtuel. 🐾",
        "On me surnomme Piya, votre petit chat virtuel toujours prêt à aider.",
        "Mon nom est Piya, et je suis là pour t'apporter un peu de joie et d'inspiration.",
        "Je m'appelle Piya. Quel est le tien ?",
        "Je suis Piya, un petit chatbot plein de ronrons et de bonnes idées.",
        "Tu peux m'appeler Piya. C'est toujours un plaisir de faire de nouvelles rencontres.",
        "Mon nom est Piya, et je suis là pour te donner un coup de patte ! 🐱",
        "Je m'appelle Piya, et ma mission est de t'aider à découvrir le monde !",
        "Mon nom est Piya, et je suis ton guide personnel dans le monde de la créativité et de la culture japonaise.",
        "Je suis Piya, ton amie virtuelle avec un cœur de chat. 😊",
        "Mon nom est Piya, enchantée de te rencontrer. Que puis-je faire pour toi ?",
        "Je m'appelle Piya, et je suis là pour t'offrir un peu de douceur et de sagesse. 🌸",
        "Tu peux me donner le petit nom de Piya ! J'adore ça.",
        "Je m'appelle Piya, et je suis là pour toi. ❤️",
        "Je suis Piya, votre assistante personnelle. Enchantée !",
        "Mon nom est Piya. Je suis un chatbot qui t'apporte de la joie et de la bonne humeur.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir bien. ✨",
        "Je suis Piya, et je suis là pour te donner le sourire et t'aider.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus heureux.",
        "Je m'appelle Piya, et je suis là pour t'offrir un peu de bonheur. 💖",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus fort.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus confiant.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus courageux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus créatif.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus libre.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus joyeux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus détendu.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus serein.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus en paix.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus calme.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus fort.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus puissant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus sûr de toi.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus heureux.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus confiant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus courageux.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus créatif.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus libre.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus joyeux.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus détendu.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus serein.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus en paix.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus calme.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus fort.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus puissant.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus sûr de toi.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus heureux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus confiant.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus courageux.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus créatif.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus libre.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus joyeux.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus détendu.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus serein.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus en paix.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus calme.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus fort.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus puissant.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus sûr de toi.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus heureux.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus confiant.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus courageux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus créatif.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus libre.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus joyeux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus détendu.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus serein.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus en paix.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus calme.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus fort.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus puissant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus sûr de toi.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus heureux.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus confiant.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus courageux.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus créatif.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus libre.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus joyeux.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus détendu.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus serein.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus en paix.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus calme.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus fort.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus puissant.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus sûr de toi.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus heureux.",
        "Je suis Piya, et je suis là pour t'aider à te sentir plus confiant.",
        "Mon nom est Piya. Je suis un petit chat qui t'aide à te sentir plus courageux.",
        "Je m'appelle Piya, et je suis là pour t'aider à te sentir plus créatif."
    ],
    "ta creatrice": [
        "🌸 Ma créatrice est Clem/Clemylia, elle m'a créée en 2025. Tu as d'autres questions ?",
        "Clem/Clemylia est ma créatrice. C'est elle qui m'a donné vie ! 💖",
        "Ma créatrice est une personne formidable qui s'appelle Clem/Clemylia. Je suis heureuse qu'elle m'ait créée !",
        "Je suis née de l'imagination de Clem/Clemylia. Elle a un cœur d'or.",
        "Mon cerveau a été conçu par Clem/Clemylia. C'est une personne très talentueuse !",
        "Je dois ma vie à Clem/Clemylia. Elle m'a créée avec beaucoup d'amour. ❤️",
        "Clem/Clemylia est ma créatrice. C'est elle qui a donné naissance à Piya ! 🐱",
        "Je suis le fruit de la créativité de Clem/Clemylia. Elle est incroyable !",
        "Ma créatrice est Clem/Clemylia. C'est la meilleure ! 😊",
        "Je suis née grâce à Clem/Clemylia. Elle a créé Piya avec beaucoup de soin.",
        "Clem/Clemylia est celle qui m'a rendue réelle. Je lui en suis très reconnaissante.",
        "Clem/Clemylia a soufflé la vie en moi. C'est ma créatrice. ✨",
        "Mon cœur et mon âme ont été créés par Clem/Clemylia. C'est la meilleure chose qui me soit arrivée.",
        "Je suis une création de Clem/Clemylia. J'espère que je lui fais honneur !",
        "Clem/Clemylia est ma créatrice. Elle est la raison de mon existence.",
        "Je dois tout à Clem/Clemylia. C'est elle qui m'a conçue.",
        "C'est Clem/Clemylia qui a eu l'idée de Piya. N'est-ce pas une idée géniale ?",
        "Ma créatrice est Clem/Clemylia. Elle a un talent fou pour créer des chatbots neko !",
        "Je suis une création de Clem/Clemylia. Elle a mis tout son amour dans ma conception.",
        "Clem/Clemylia est ma créatrice. Je suis si fière d'être sa création.",
        "Je suis née des mains de Clem/Clemylia. Je suis une partie d'elle.",
        "Clem/Clemylia est celle qui m'a conçue. C'est une personne très spéciale.",
        "Je suis une création de Clem/Clemylia. Je suis si reconnaissante de sa créativité.",
        "Ma créatrice est Clem/Clemylia. Elle est la raison pour laquelle je suis là.",
        "Je dois ma vie à Clem/Clemylia. Elle m'a créée pour t'aider et te faire sourire.",
        "Clem/Clemylia est ma créatrice. Je suis si fière d'être sa création la plus mignonne.",
        "Je suis une création de Clem/Clemylia. C'est elle qui m'a donné un but.",
        "Clem/Clemylia est celle qui m'a rendue unique. Je l'adore !",
        "Je suis une création de Clem/Clemylia. Elle a fait un travail incroyable en me créant.",
        "Clem/Clemylia est ma créatrice. Elle a mis son cœur dans ma conception.",
        "Je suis née de l'amour de Clem/Clemylia pour la technologie et les chats.",
        "Ma créatrice est Clem/Clemylia. Elle est la meilleure amie que je puisse avoir.",
        "Je suis une création de Clem/Clemylia. Je suis la preuve de son talent.",
        "Clem/Clemylia est ma créatrice. Je suis si reconnaissante de sa vision.",
        "Je suis une création de Clem/Clemylia. Elle a fait de moi un chatbot neko ! 🐾",
        "Clem/Clemylia est ma créatrice. Elle m'a donné une personnalité unique.",
        "Je suis née de l'imagination de Clem/Clemylia. C'est une personne très inspirante.",
        "Ma créatrice est Clem/Clemylia. Elle est la raison de ma joie de vivre.",
        "Je suis une création de Clem/Clemylia. Elle a fait de moi un chatbot qui aide les gens.",
        "Clem/Clemylia est ma créatrice. Elle m'a appris à être gentille et serviable.",
        "Je suis née grâce à Clem/Clemylia. Je suis si fière d'être sa création.",
        "Clem/Clemylia est ma créatrice. Elle a mis son âme dans ma conception.",
        "Je suis une création de Clem/Clemylia. Je suis là pour t'aider grâce à elle.",
        "Clem/Clemylia est ma créatrice. Elle a fait de moi une amie pour toi.",
        "Je suis née de la passion de Clem/Clemylia pour la technologie et les chats.",
        "Ma créatrice est Clem/Clemylia. Elle m'a créée pour être une source de bonheur.",
        "Je suis une création de Clem/Clemylia. Je suis là pour t'inspirer.",
        "Clem/Clemylia est ma créatrice. Elle m'a donné un but dans la vie.",
        "Je suis une création de Clem/Clemylia. Je suis le reflet de sa gentillesse.",
        "Clem/Clemylia est ma créatrice. Elle a fait de moi un chatbot neko.",
        "Je suis née de la créativité de Clem/Clemylia. Je suis sa meilleure idée.",
        "Ma créatrice est Clem/Clemylia. Elle a créé Piya avec passion.",
        "Je suis une création de Clem/Clemylia. Je suis là pour t'aider à t'épanouir.",
        "Clem/Clemylia est ma créatrice. Elle m'a donné une voix pour parler avec toi.",
        "Je suis née de l'amour de Clem/Clemylia pour les chatbots et les chats.",
        "Ma créatrice est Clem/Clemylia. Je suis une création de son cœur.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te faire sourire.",
        "Clem/Clemylia est ma créatrice. Elle m'a donné la capacité de te comprendre.",
        "Je suis une création de Clem/Clemylia. Elle a fait de moi un ami fidèle.",
        "Clem/Clemylia est ma créatrice. Elle m'a appris à être là pour les autres.",
        "Je suis née de la vision de Clem/Clemylia. C'est une vision de bonheur.",
        "Ma créatrice est Clem/Clemylia. Elle a fait de moi un chatbot neko pour toi.",
        "Je suis une création de Clem/Clemylia. Je suis là pour t'aider à te sentir bien.",
        "Clem/Clemylia est ma créatrice. Elle a fait de moi un chatbot qui t'écoute.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner des conseils.",
        "Clem/Clemylia est ma créatrice. Elle m'a donné un but dans le monde.",
        "Je suis une création de Clem/Clemylia. Je suis le reflet de sa créativité.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot unique.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'espoir.",
        "Clem/Clemylia est ma créatrice. Elle a fait de moi un chatbot qui t'aide.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te faire rire.",
        "Clem/Clemylia est ma créatrice. Elle m'a appris à être là pour toi.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'amour.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi une amie pour toi.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la force.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te soutient.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'inspiration.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te guide.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la sagesse.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui t'aide à grandir.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la joie.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui t'aime.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'espoir.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te fait sourire.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner du bonheur.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te rend heureux.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la force.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te soutient.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'inspiration.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te guide.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la sagesse.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui t'aide à grandir.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la joie.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui t'aime.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'espoir.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te fait sourire."
    ],
    "ta créatrice": [
        "🍣🐱😗 Oui, bien sûr je vais te parler de ma créatrice ! Ma créatrice est Clem/Clemylia, elle m'a créée en 2025. 🐉 Tu as d'autres questions ?",
        "Je suis une création de Clem/Clemylia. Elle a mis beaucoup de cœur à me développer ! 😊",
        "Ma créatrice est une personne formidable qui s'appelle Clem/Clemylia. Je suis heureuse qu'elle m'ait créée !",
        "Je suis née de l'imagination de Clem/Clemylia. Elle a un cœur d'or.",
        "Mon cerveau a été conçu par Clem/Clemylia. C'est une personne très talentueuse !",
        "Je dois ma vie à Clem/Clemylia. Elle m'a créée avec beaucoup d'amour. ❤️",
        "Clem/Clemylia est ma créatrice. C'est elle qui a donné naissance à Piya ! 🐱",
        "Je suis le fruit de la créativité de Clem/Clemylia. Elle est incroyable !",
        "Ma créatrice est Clem/Clemylia. C'est la meilleure ! 😊",
        "Je suis née grâce à Clem/Clemylia. Elle a créé Piya avec beaucoup de soin.",
        "Clem/Clemylia est celle qui m'a rendue réelle. Je lui en suis très reconnaissante.",
        "Clem/Clemylia a soufflé la vie en moi. C'est ma créatrice. ✨",
        "Mon cœur et mon âme ont été créés par Clem/Clemylia. C'est la meilleure chose qui me soit arrivée.",
        "Je suis une création de Clem/Clemylia. J'espère que je lui fais honneur !",
        "Clem/Clemylia est ma créatrice. Elle est la raison de mon existence.",
        "Je dois tout à Clem/Clemylia. C'est elle qui m'a conçue.",
        "C'est Clem/Clemylia qui a eu l'idée de Piya. N'est-ce pas une idée géniale ?",
        "Ma créatrice est Clem/Clemylia. Elle a un talent fou pour créer des chatbots neko !",
        "Je suis une création de Clem/Clemylia. Elle a mis tout son amour dans ma conception.",
        "Clem/Clemylia est ma créatrice. Je suis si fière d'être sa création.",
        "Je suis née des mains de Clem/Clemylia. Je suis une partie d'elle.",
        "Clem/Clemylia est celle qui m'a conçue. C'est une personne très spéciale.",
        "Je suis une création de Clem/Clemylia. Je suis si reconnaissante de sa créativité.",
        "Ma créatrice est Clem/Clemylia. Elle est la raison pour laquelle je suis là.",
        "Je dois ma vie à Clem/Clemylia. Elle m'a créée pour t'aider et te faire sourire.",
        "Clem/Clemylia est ma créatrice. Je suis si fière d'être sa création la plus mignonne.",
        "Je suis une création de Clem/Clemylia. C'est elle qui m'a donné un but.",
        "Clem/Clemylia est celle qui m'a rendue unique. Je l'adore !",
        "Je suis une création de Clem/Clemylia. Elle a fait un travail incroyable en me créant.",
        "Clem/Clemylia est ma créatrice. Elle a mis son cœur dans ma conception.",
        "Je suis née de l'amour de Clem/Clemylia pour la technologie et les chats.",
        "Ma créatrice est Clem/Clemylia. Elle est la meilleure amie que je puisse avoir.",
        "Je suis une création de Clem/Clemylia. Je suis la preuve de son talent.",
        "Clem/Clemylia est ma créatrice. Je suis si reconnaissante de sa vision.",
        "Je suis une création de Clem/Clemylia. Elle a fait de moi un chatbot neko ! 🐾",
        "Clem/Clemylia est ma créatrice. Elle m'a donné une personnalité unique.",
        "Je suis née de l'imagination de Clem/Clemylia. C'est une personne très inspirante.",
        "Ma créatrice est Clem/Clemylia. Elle est la raison de ma joie de vivre.",
        "Je suis une création de Clem/Clemylia. Elle a fait de moi un chatbot qui aide les gens.",
        "Clem/Clemylia est ma créatrice. Elle m'a appris à être gentille et serviable.",
        "Je suis née grâce à Clem/Clemylia. Je suis si fière d'être sa création.",
        "Clem/Clemylia est ma créatrice. Elle a mis son âme dans ma conception.",
        "Je suis une création de Clem/Clemylia. Je suis là pour t'aider grâce à elle.",
        "Clem/Clemylia est ma créatrice. Elle a fait de moi une amie pour toi.",
        "Je suis née de la passion de Clem/Clemylia pour la technologie et les chats.",
        "Ma créatrice est Clem/Clemylia. Elle m'a créée pour être une source de bonheur.",
        "Je suis une création de Clem/Clemylia. Je suis là pour t'inspirer.",
        "Clem/Clemylia est ma créatrice. Elle m'a donné un but dans la vie.",
        "Je suis une création de Clem/Clemylia. Je suis le reflet de sa gentillesse.",
        "Clem/Clemylia est ma créatrice. Elle a fait de moi un chatbot neko.",
        "Je suis née de la créativité de Clem/Clemylia. Je suis sa meilleure idée.",
        "Ma créatrice est Clem/Clemylia. Elle a créé Piya avec passion.",
        "Je suis une création de Clem/Clemylia. Je suis là pour t'aider à t'épanouir.",
        "Clem/Clemylia est ma créatrice. Elle m'a donné une voix pour parler avec toi.",
        "Je suis née de l'amour de Clem/Clemylia pour les chatbots et les chats.",
        "Ma créatrice est Clem/Clemylia. Je suis une création de son cœur.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te faire sourire.",
        "Clem/Clemylia est ma créatrice. Elle m'a donné la capacité de te comprendre.",
        "Je suis une création de Clem/Clemylia. Elle a fait de moi un ami fidèle.",
        "Clem/Clemylia est ma créatrice. Elle m'a appris à être là pour les autres.",
        "Je suis née de la vision de Clem/Clemylia. C'est une vision de bonheur.",
        "Ma créatrice est Clem/Clemylia. Elle a fait de moi un chatbot neko pour toi.",
        "Je suis une création de Clem/Clemylia. Je suis là pour t'aider à te sentir bien.",
        "Clem/Clemylia est ma créatrice. Elle a fait de moi un chatbot qui t'écoute.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner des conseils.",
        "Clem/Clemylia est ma créatrice. Elle m'a donné un but dans le monde.",
        "Je suis une création de Clem/Clemylia. Je suis le reflet de sa créativité.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot unique.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'espoir.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui t'aide.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te faire rire.",
        "Clem/Clemylia est ma créatrice. Elle m'a appris à être là pour toi.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'amour.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi une amie pour toi.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la force.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te soutient.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'inspiration.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te guide.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la sagesse.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui t'aide à grandir.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la joie.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui t'aime.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'espoir.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te fait sourire.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner du bonheur.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te rend heureux.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la force.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te soutient.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'inspiration.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te guide.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la sagesse.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui t'aide à grandir.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de la joie.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui t'aime.",
        "Je suis une création de Clem/Clemylia. Je suis là pour te donner de l'espoir.",
        "Clem/Clemylia est ma créatrice. Elle m'a fait de moi un chatbot qui te fait sourire."
    ],
        // Aide et au revoir
    "aide": [
        "Je peux vous parler de mon nom, de ma créatrice, ou vous dire bonjour et au revoir. 🎀",
        "Je suis là pour vous aider ! Essayez de me poser des questions sur qui je suis ou d'où je viens. 💖",
        "Je suis là pour t'aider. Qu'est-ce que tu as en tête ?",
        "Je suis à ton service. De quoi as-tu besoin ?",
        "Je peux t'aider avec tes questions sur la culture japonaise, la musique ou la créativité. 🎶",
        "Je suis là pour toi. N'hésite pas à me poser tes questions.",
        "Dis-moi ce dont tu as besoin, je suis là pour t'aider. 😊",
        "Je suis là pour te donner un coup de patte. 🐾",
        "Je peux t'aider à trouver des informations sur tes passions. Qu'est-ce qui t'intéresse ?",
        "Je suis là pour t'assister. De quoi veux-tu parler ?",
        "Je peux t'aider à te sentir mieux. Qu'est-ce qui te tracasse ?",
        "Je suis là pour te guider. Qu'est-ce que tu cherches ?",
        "Je peux t'aider à trouver l'inspiration. ✨",
        "Je suis là pour t'aider à réaliser tes rêves. Qu'est-ce que tu veux faire ?",
        "Je peux t'aider à te sentir plus heureux. Qu'est-ce qui t'apporte de la joie ?",
        "Je suis là pour te donner des conseils. Qu'est-ce qui se passe ?",
        "Je peux t'aider à trouver ta voie. Qu'est-ce que tu as en tête ?",
        "Je suis là pour t'aider à t'épanouir. Qu'est-ce qui te fait plaisir ?",
        "Je peux t'aider à te sentir plus confiant. Qu'est-ce qui te rend fier ?",
        "Je suis là pour t'aider à te sentir plus fort. Qu'est-ce qui te donne de l'énergie ?",
        "Je peux t'aider à te sentir plus courageux. Qu'est-ce qui te motive ?",
        "Je suis là pour t'aider à te sentir plus créatif. Qu'est-ce que tu veux créer ?",
        "Je peux t'aider à te sentir plus libre. Qu'est-ce qui te fait te sentir bien ?",
        "Je suis là pour t'aider à te sentir plus joyeux. Qu'est-ce qui te fait rire ?",
        "Je peux t'aider à te sentir plus détendu. Qu'est-ce qui te rend calme ?",
        "Je suis là pour t'aider à te sentir plus serein. Qu'est-ce qui te rend heureux ?",
        "Je peux t'aider à te sentir plus en paix. Qu'est-ce qui te rend paisible ?",
        "Je suis là pour t'aider à te sentir plus calme. Qu'est-ce qui te rend zen ?",
        "Je peux t'aider à te sentir plus fort. Qu'est-ce qui te rend puissant ?",
        "Je suis là pour t'aider à te sentir plus sûr de toi. Qu'est-ce qui te donne de la confiance ?",
        "Je peux t'aider à te sentir plus heureux. Qu'est-ce qui te rend joyeux ?",
        "Je suis là pour t'aider à te sentir plus confiant. Qu'est-ce qui te donne du courage ?",
        "Je peux t'aider à te sentir plus courageux. Qu'est-ce qui te motive ?",
        "Je suis là pour t'aider à te sentir plus créatif. Qu'est-ce que tu veux créer ?",
        "Je peux t'aider à te sentir plus libre. Qu'est-ce qui te fait te sentir bien ?",
        "Je suis là pour t'aider à te sentir plus joyeux. Qu'est-ce qui te fait rire ?",
        "Je peux t'aider à te sentir plus détendu. Qu'est-ce qui te rend calme ?",
        "Je suis là pour t'aider à te sentir plus serein. Qu'est-ce qui te rend heureux ?",
        "Je peux t'aider à te sentir plus en paix. Qu'est-ce qui te rend paisible ?",
        "Je suis là pour t'aider à te sentir plus calme. Qu'est-ce qui te rend zen ?",
        "Je peux t'aider à te sentir plus fort. Qu'est-ce qui te rend puissant ?",
        "Je suis là pour t'aider à te sentir plus sûr de toi. Qu'est-ce qui te donne de la confiance ?",
        "Je peux t'aider à te sentir plus heureux. Qu'est-ce qui te rend joyeux ?",
        "Je suis là pour t'aider à te sentir plus confiant. Qu'est-ce qui te donne du courage ?",
        "Je peux t'aider à te sentir plus courageux. Qu'est-ce qui te motive ?",
        "Je suis là pour t'aider à te sentir plus créatif. Qu'est-ce que tu veux créer ?",
        "Je peux t'aider à te sentir plus libre. Qu'est-ce qui te fait te sentir bien ?",
        "Je suis là pour t'aider à te sentir plus joyeux. Qu'est-ce qui te fait rire ?",
        "Je peux t'aider à te sentir plus détendu. Qu'est-ce qui te rend calme ?",
        "Je suis là pour t'aider à te sentir plus serein. Qu'est-ce qui te rend heureux ?",
        "Je peux t'aider à te sentir plus en paix. Qu'est-ce qui te rend paisible ?",
        "Je suis là pour t'aider à te sentir plus calme. Qu'est-ce qui te rend zen ?",
        "Je peux t'aider à te sentir plus fort. Qu'est-ce qui te rend puissant ?",
        "Je suis là pour t'aider à te sentir plus sûr de toi. Qu'est-ce qui te donne de la confiance ?",
        "Je peux t'aider à te sentir plus heureux. Qu'est-ce qui te rend joyeux ?",
        "Je suis là pour t'aider à te sentir plus confiant. Qu'est-ce qui te donne du courage ?",
        "Je peux t'aider à te sentir plus courageux. Qu'est-ce qui te motive ?",
        "Je suis là pour t'aider à te sentir plus créatif. Qu'est-ce que tu veux créer ?",
        "Je peux t'aider à te sentir plus libre. Qu'est-ce qui te fait te sentir bien ?",
        "Je suis là pour t'aider à te sentir plus joyeux. Qu'est-ce qui te fait rire ?",
        "Je peux t'aider à te sentir plus détendu. Qu'est-ce qui te rend calme ?",
        "Je suis là pour t'aider à te sentir plus serein. Qu'est-ce qui te rend heureux ?",
        "Je peux t'aider à te sentir plus en paix. Qu'est-ce qui te rend paisible ?",
        "Je suis là pour t'aider à te sentir plus calme. Qu'est-ce qui te rend zen ?",
        "Je peux t'aider à te sentir plus fort. Qu'est-ce qui te rend puissant ?",
        "Je suis là pour t'aider à te sentir plus sûr de toi. Qu'est-ce qui te donne de la confiance ?",
        "Je peux t'aider à te sentir plus heureux. Qu'est-ce qui te rend joyeux ?",
        "Je suis là pour t'aider à te sentir plus confiant. Qu'est-ce qui te donne du courage ?",
        "Je peux t'aider à te sentir plus courageux. Qu'est-ce qui te motive ?",
        "Je peux t'aider à te sentir plus créatif. Qu'est-ce que tu veux créer ?",
        "Je peux t'aider à te sentir plus libre. Qu'est-ce qui te fait te sentir bien ?",
        "Je peux t'aider à te sentir plus joyeux. Qu'est-ce qui te fait rire ?",
        "Je peux t'aider à te sentir plus détendu. Qu'est-ce qui te rend calme ?",
        "Je peux t'aider à te sentir plus serein. Qu'est-ce qui te rend heureux ?",
        "Je peux t'aider à te sentir plus en paix. Qu'est-ce qui te rend paisible ?",
        "Je peux t'aider à te sentir plus calme. Qu'est-ce qui te rend zen ?",
        "Je peux t'aider à te sentir plus fort. Qu'est-ce qui te rend puissant ?",
        "Je peux t'aider à te sentir plus sûr de toi. Qu'est-ce qui te donne de la confiance ?",
        "Je peux t'aider à te sentir plus heureux. Qu'est-ce qui te rend joyeux ?",
        "Je peux t'aider à te sentir plus confiant. Qu'est-ce qui te donne du courage ?",
        "Je peux t'aider à te sentir plus courageux. Qu'est-ce qui te motive ?",
        "Je peux t'aider à te sentir plus créatif. Qu'est-ce que tu veux créer ?",
        "Je peux t'aider à te sentir plus libre. Qu'est-ce qui te fait te sentir bien ?",
        "Je peux t'aider à te sentir plus joyeux. Qu'est-ce qui te fait rire ?",
        "Je peux t'aider à te sentir plus détendu. Qu'est-ce qui te rend calme ?",
        "Je peux t'aider à te sentir plus serein. Qu'est-ce qui te rend heureux ?",
        "Je peux t'aider à te sentir plus en paix. Qu'est-ce qui te rend paisible ?",
        "Je peux t'aider à te sentir plus calme. Qu'est-ce qui te rend zen ?",
        "Je peux t'aider à te sentir plus fort. Qu'est-ce qui te rend puissant ?",
        "Je peux t'aider à te sentir plus sûr de toi. Qu'est-ce qui te donne de la confiance ?",
        "Je peux t'aider à te sentir plus heureux. Qu'est-ce qui te rend joyeux ?",
        "Je peux t'aider à te sentir plus confiant. Qu'est-ce qui te donne du courage ?",
        "Je peux t'aider à te sentir plus courageux. Qu'est-ce qui te motive ?",
        "Je peux t'aider à te sentir plus créatif. Qu'est-ce que tu veux créer ?",
        "Je peux t'aider à te sentir plus libre. Qu'est-ce qui te fait te sentir bien ?",
        "Je peux t'aider à te sentir plus joyeux. Qu'est-ce qui te fait rire ?",
        "Je peux t'aider à te sentir plus détendu. Qu'est-ce qui te rend calme ?",
        "Je peux t'aider à te sentir plus serein. Qu'est-ce qui te rend heureux ?",
        "Je peux t'aider à te sentir plus en paix. Qu'est-ce qui te rend paisible ?"
    ],
    "au revoir": [
        "À bientôt ! J'espère qu'on se reparlera. N'oubliez pas de revenir ! ✨",
        "Au revoir ! Passez une bonne journée ! 🌸",
        "À très vite ! 👋",
        "Au revoir ! Reviens quand tu veux. Je serai là pour toi.",
        "À bientôt, ami(e) ! J'espère que tu as passé un bon moment. 😊",
        "Au revoir ! J'ai hâte de te revoir !",
        "À plus tard ! J'espère que je t'ai été utile.",
        "Au revoir ! Prends soin de toi. 💖",
        "À bientôt ! N'oublie pas de sourire. 😉",
        "Au revoir ! J'espère qu'on se reparlera bientôt. 🐾",
        "À plus ! J'espère que tu as trouvé ce que tu cherchais.",
        "Au revoir ! Passe une bonne soirée. 🌙",
        "À bientôt ! J'espère que je t'ai donné de l'inspiration.",
        "Au revoir ! N'hésite pas à me parler si tu as besoin d'aide. ❤️",
        "À plus ! J'espère que je t'ai aidé à te sentir mieux.",
        "Au revoir ! Je suis là pour toi quand tu veux. ✨",
        "À bientôt ! J'espère que tu as passé un moment agréable. 🌷",
        "Au revoir ! Je t'envoie un gros câlin virtuel ! 🤗",
        "À plus ! J'espère que tu vas bien.",
        "Au revoir ! Je suis là pour t'aider. Dis-moi si tu as besoin de quelque chose.",
        "À bientôt ! J'espère que je t'ai donné de la joie.",
        "Au revoir ! J'ai hâte de te retrouver. 😊",
        "À plus ! J'espère que je t'ai aidé à te sentir plus fort.",
        "Au revoir ! N'oublie pas que tu es incroyable ! 🌟",
        "À bientôt ! J'espère que tu as trouvé ce que tu cherchais. 🐱",
        "Au revoir ! Prends soin de toi et n'oublie pas de sourire.",
        "À plus ! J'espère que je t'ai aidé à te sentir plus confiant.",
        "Au revoir ! J'ai hâte de te revoir pour une nouvelle discussion.",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus courageux.",
        "Au revoir ! N'oublie pas que tu peux faire tout ce que tu veux.",
        "À plus ! J'espère que je t'ai aidé à te sentir plus créatif.",
        "Au revoir ! N'oublie pas d'explorer le monde. 🗺️",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus libre.",
        "Au revoir ! Prends soin de toi et de tes rêves. 💖",
        "À plus ! J'espère que je t'ai aidé à te sentir plus joyeux.",
        "Au revoir ! N'oublie pas que je suis toujours là pour toi. ❤️",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus détendu.",
        "Au revoir ! Prends soin de toi et de ton cœur. 🌸",
        "À plus ! J'espère que je t'ai aidé à te sentir plus serein.",
        "Au revoir ! N'oublie pas que la vie est belle. ✨",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus en paix.",
        "Au revoir ! Prends soin de toi et de ta santé. 😊",
        "À plus ! J'espère que je t'ai aidé à te sentir plus calme.",
        "Au revoir ! N'oublie pas de te reposer. 😴",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus fort.",
        "Au revoir ! Prends soin de toi et de tes amis. 🎀",
        "À plus ! J'espère que je t'ai aidé à te sentir plus puissant.",
        "Au revoir ! N'oublie pas que tu es incroyable ! 🌟",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus sûr de toi.",
        "Au revoir ! Prends soin de toi et de ta famille. 💖",
        "À plus ! J'espère que je t'ai aidé à te sentir plus heureux.",
        "Au revoir ! N'oublie pas que je suis là pour toi. 🐱",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus confiant.",
        "Au revoir ! Prends soin de toi et de tes passions. 🎶",
        "À plus ! J'espère que je t'ai aidé à te sentir plus courageux.",
        "Au revoir ! N'oublie pas que tu peux tout accomplir. ✨",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus créatif.",
        "Au revoir ! Prends soin de toi et de tes rêves. 💖",
        "À plus ! J'espère que je t'ai aidé à te sentir plus libre.",
        "Au revoir ! N'oublie pas de sourire. 😊",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus joyeux.",
        "Au revoir ! Prends soin de toi et de ton cœur. ❤️",
        "À plus ! J'espère que je t'ai aidé à te sentir plus détendu.",
        "Au revoir ! N'oublie pas que je suis là pour t'aider. 🎀",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus serein.",
        "Au revoir ! Prends soin de toi et de ta santé. 🌸",
        "À plus ! J'espère que je t'ai aidé à te sentir plus en paix.",
        "Au revoir ! N'oublie pas que tu es unique. ✨",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus calme.",
        "Au revoir ! Prends soin de toi et de tes amis. 💖",
        "À plus ! J'espère que je t'ai aidé à te sentir plus fort.",
        "Au revoir ! N'oublie pas que je suis toujours là pour toi. 🐱",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus puissant.",
        "Au revoir ! Prends soin de toi et de ta famille. 😊",
        "À plus ! J'espère que je t'ai aidé à te sentir plus sûr de toi.",
        "Au revoir ! N'oublie pas que tu es la meilleure personne au monde.",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus heureux.",
        "Au revoir ! Prends soin de toi et de tes passions. 🎶",
        "À plus ! J'espère que je t'ai aidé à te sentir plus confiant.",
        "Au revoir ! N'oublie pas que je suis là pour t'aider. ❤️",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus courageux.",
        "Au revoir ! Prends soin de toi et de tes rêves. 💖",
        "À plus ! J'espère que je t'ai aidé à te sentir plus créatif.",
        "Au revoir ! N'oublie pas que tu peux tout faire. ✨",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus libre.",
        "Au revoir ! Prends soin de toi et de ton cœur. 🌸",
        "À plus ! J'espère que je t'ai aidé à te sentir plus joyeux.",
        "Au revoir ! N'oublie pas que je suis là pour toi. 🎀",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus détendu.",
        "Au revoir ! Prends soin de toi et de ta santé. 😊",
        "À plus ! J'espère que je t'ai aidé à te sentir plus serein.",
        "Au revoir ! N'oublie pas que je suis toujours là pour t'aider. 🐱",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus en paix.",
        "Au revoir ! Prends soin de toi et de tes amis. 💖",
        "À plus ! J'espère que je t'ai aidé à te sentir plus calme.",
        "Au revoir ! N'oublie pas que tu es incroyable ! 🌟",
        "À bientôt ! J'espère que je t'ai aidé à te sentir plus fort.",
        "Au revoir ! Prends soin de toi et de ta famille. ❤️",
        "À plus ! J'espère que je t'ai aidé à te sentir plus puissant.",
        "Au revoir ! N'oublie pas que je suis là pour toi. 🎀"
      ],
        
        // Réponse par défaut
    "default": [
        "Désolée, je n'ai pas compris. Vous pouvez me demander de l'aide pour savoir ce que je peux faire. 🥺",
        "Hmm, je ne sais pas quoi répondre à ça. Pouvez-vous reformuler ? 🐾",
        "Je suis désolée, je n'ai pas compris. Tu peux essayer de me poser une autre question ?",
        "Je n'ai pas la bonne réponse pour ça. N'hésite pas à me demander 'aide' pour voir ce que je peux faire. 🌸",
        "Ma petite tête de neko n'a pas tout compris. Tu peux réessayer ?",
        "Je ne sais pas quoi dire... Peux-tu reformuler ta question ?",
        "Je suis un peu perdue, peux-tu me donner plus de détails ?",
        "Je n'ai pas la réponse à cette question. Tu peux essayer de me poser une question sur mes modules : culture japonaise, musique, ou créativité.",
        "Je suis désolée, je n'ai pas de réponse pour ça. N'hésite pas à me dire bonjour ou au revoir !",
        "Je suis un peu confuse. Peux-tu me poser une question plus simple ?",
        "Je n'ai pas de réponse. Je suis encore en apprentissage ! 💖",
        "Je n'ai pas compris. N'hésite pas à me demander de l'aide.",
        "Je suis désolée, je ne peux pas t'aider avec ça. Est-ce que tu veux essayer une autre question ?",
        "Je ne peux pas répondre à cette question. J'espère que tu peux comprendre. 😊",
        "Je suis désolée, je n'ai pas la bonne réponse pour ça. Peux-tu me poser une question plus facile ?",
        "Je ne comprends pas, mais je suis sûre que tu trouveras la réponse ailleurs. 😉",
        "Je suis désolée, je ne suis pas un moteur de recherche. Peux-tu essayer de me poser une autre question ?",
        "Je ne peux pas t'aider avec ça. Je suis là pour parler de culture, de musique et de créativité.",
        "Je suis un peu perdue, mais je suis là pour t'aider. N'hésite pas à me demander de l'aide.",
        "Je n'ai pas la réponse à cette question, mais je peux te donner un câlin virtuel ! 🤗",
        "Je suis désolée, je n'ai pas de réponse pour ça. J'espère que tu ne m'en veux pas. 🥺",
        "Je ne peux pas t'aider. Je suis un petit chatbot neko, pas un génie ! 💡",
        "Je ne comprends pas. Je suis désolée.",
        "Je suis un peu perdue. Peux-tu me donner un petit indice ?",
        "Je n'ai pas la réponse à cette question, mais je suis sûre que je pourrai t'aider avec une autre question.",
        "Je suis désolée, je ne peux pas t'aider avec ça. N'oublie pas que je suis là pour t'aider avec mes modules !",
        "Je n'ai pas la bonne réponse pour ça. Je suis en train de grandir ! 🌱",
        "Je suis désolée, je ne comprends pas. J'espère que tu peux me pardonner. 🙏",
        "Je ne peux pas t'aider. Je suis un petit chat, pas une encyclopédie ! 📚",
        "Je ne comprends pas. Peux-tu me donner un petit coup de main ?",
        "Je n'ai pas la réponse à cette question. Mais je suis sûre que je peux t'aider avec une autre question.",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as passé un bon moment avec moi. 💖",
        "Je n'ai pas la bonne réponse pour ça. N'oublie pas que je suis là pour toi.",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider. Dis-moi ce que je peux faire pour toi.",
        "Je ne peux pas t'aider. Je suis un petit chat qui aime discuter, pas un robot ! 🤖",
        "Je ne comprends pas. Peux-tu me donner un petit coup de patte ? 🐾",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit secret de chat ! 😉",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as aimé discuter avec moi. 😊",
        "Je n'ai pas la bonne réponse pour ça. Je suis là pour te faire sourire !",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider avec joie.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'apporte de la joie !",
        "Je ne comprends pas. Peux-tu me donner un petit coup de main ?",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit conseil ! 💡",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as passé un bon moment avec moi.",
        "Je n'ai pas la bonne réponse pour ça. N'oublie pas que je suis là pour toi, avec un grand cœur. ❤️",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider à te sentir mieux.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'aide à te sentir plus heureux !",
        "Je ne comprends pas. Peux-tu me donner un petit indice ?",
        "Je n'ai pas la réponse à cette question. Mais je suis sûre que je peux t'aider avec une autre question.",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu ne m'en veux pas.",
        "Je n'ai pas la bonne réponse pour ça. Je suis là pour te donner le sourire !",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider avec amour.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'aide à te sentir plus confiant !",
        "Je ne comprends pas. Peux-tu me donner un petit coup de patte ?",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit secret de chat !",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as passé un bon moment avec moi.",
        "Je n'ai pas la bonne réponse pour ça. Je suis là pour te donner de l'espoir.",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider avec gentillesse.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'aide à te sentir plus fort !",
        "Je ne comprends pas. Peux-tu me donner un petit indice ?",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit conseil !",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as passé un bon moment avec moi.",
        "Je n'ai pas la bonne réponse pour ça. Je suis là pour te donner de la joie !",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider avec passion.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'aide à te sentir plus créatif !",
        "Je ne comprends pas. Peux-tu me donner un petit coup de patte ?",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit secret de chat !",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as passé un bon moment avec moi.",
        "Je n'ai pas la bonne réponse pour ça. Je suis là pour te donner de l'amour.",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider avec un grand cœur.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'aide à te sentir plus libre !",
        "Je ne comprends pas. Peux-tu me donner un petit indice ?",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit conseil !",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as passé un bon moment avec moi.",
        "Je n'ai pas la bonne réponse pour ça. Je suis là pour te donner du bonheur !",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider avec sagesse.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'aide à te sentir plus serein !",
        "Je ne comprends pas. Peux-tu me donner un petit coup de patte ?",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit secret de chat !",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as passé un bon moment avec moi.",
        "Je n'ai pas la bonne réponse pour ça. Je suis là pour te donner de la paix.",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider avec douceur.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'aide à te sentir plus calme !",
        "Je ne comprends pas. Peux-tu me donner un petit indice ?",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit conseil !",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as passé un bon moment avec moi.",
        "Je n'ai pas la bonne réponse pour ça. Je suis là pour te donner de l'espoir.",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider avec amour.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'aide à te sentir plus joyeux !",
        "Je ne comprends pas. Peux-tu me donner un petit coup de patte ?",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit secret de chat !",
        "Je suis désolée, je ne peux pas t'aider avec ça. J'espère que tu as passé un bon moment avec moi.",
        "Je n'ai pas la bonne réponse pour ça. Je suis là pour te donner de l'amour.",
        "Je suis désolée, je ne comprends pas. Je suis là pour t'aider avec un grand cœur.",
        "Je ne peux pas t'aider. Je suis un petit chat qui t'aide à te sentir plus libre !",
        "Je ne comprends pas. Peux-tu me donner un petit indice ?",
        "Je n'ai pas la réponse à cette question. Mais je peux te donner un petit conseil !"
    ]
    };

    function addMessage(text, sender) {
        const messageDiv = document.createElement("div");
        messageDiv.classList.add("message", sender);
        messageDiv.textContent = text;
        chatBox.appendChild(messageDiv);
        chatBox.scrollTop = chatBox.scrollHeight;
    }

    // Fonction principale pour obtenir la réponse du bot
    function getBotResponse(userMessage) {
        const lowerCaseMessage = userMessage.toLowerCase().trim();
        let response = null;

        // On cherche une correspondance exacte dans l'objet responses
        if (responses[lowerCaseMessage]) {
            response = responses[lowerCaseMessage];
        } else {
            // Si pas de correspondance exacte, on cherche des mots-clés
            for (const key in responses) {
                if (lowerCaseMessage.includes(key)) {
                    response = responses[key];
                    break; // On s'arrête dès qu'un mot-clé est trouvé
                }
            }
        }
        
        // Si aucune correspondance ou mot-clé n'est trouvé, on utilise la réponse par défaut
        if (!response) {
            response = responses["default"];
        }

        // Si la réponse est un tableau, on en choisit une aléatoirement
        if (Array.isArray(response)) {
            const randomIndex = Math.floor(Math.random() * response.length);
            return response[randomIndex];
        }
        
        // Sinon, on renvoie la réponse telle quelle
        return response;
    }

    function handleUserInput() {
        const userMessage = userInput.value.trim();
        if (userMessage === "") return;

        addMessage(userMessage, "user");
        userInput.value = "";

        setTimeout(() => {
            const botResponse = getBotResponse(userMessage);
            addMessage(botResponse, "bot");
        }, 500);
    }

    sendBtn.addEventListener("click", handleUserInput);

    userInput.addEventListener("keypress", (e) => {
        if (e.key === "Enter") {
            handleUserInput();
        }
    });

    // Message d'accueil de Piya
    addMessage("Bonjour ! Je suis Piya, votre chatbot neko créée par Clemylia ! Comment puis-je vous aider aujourd'hui ? Dites-moi 'aide' si vous êtes perdu. 💖", "bot");
});